name: astro-web-template
type: php
php_version: "8.2"
webserver_type: nginx-fpm
docroot: dist
nodejs_version: "20"

web_extra_exposed_ports:
  - name: astro-dev
    container_port: 4321
    http_port: 4321
    https_port: 4322

hooks:
  post-start:
    - exec: "if [ ! -d /var/www/html/node_modules ]; then npm install; fi"
